/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Herramientas.CargadorDeRecursos;
import Herramientas.Constantes;
import Sprite.Personaje;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import static javafx.scene.input.KeyCode.Y;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Desarrollo
 */
public class pSelectLevel extends javax.swing.JPanel {
    int xPersonaje, yPersonaje;
    int AlturaP,CuartoDeAltura;
    private Cursor cursor;
    private Point posicion;
    public int ladoCursor;
    /**
     * Creates new form selectLevel
     */
    public pSelectLevel() {
        initComponents();
        setFocusable(true);
        Puertas();
        
    }

    private void cursor(){
        Toolkit configuracion = Toolkit.getDefaultToolkit();
		final BufferedImage iconoCargado = CargadorDeRecursos
				.cargarImagenCompatibleTranslucida("/img/Personaje.png");
		ladoCursor = iconoCargado.getHeight();
		BufferedImage icono = iconoCargado;
		Point punta = new Point(0, 0);
		this.cursor = configuracion.createCustomCursor(icono, punta, "Cursor por defecto");
                main frame = (main) SwingUtilities.getWindowAncestor(this);
                frame.setCursor(cursor);
    }
    public void paint(Graphics g) {
                AlturaD();
                Puertas();
		super.paint(g);
		Graphics2D g2d = (Graphics2D) g;
		g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
				RenderingHints.VALUE_ANTIALIAS_ON);
		g.fillRect(0, CuartoDeAltura+62 , this.getWidth()-150, 4);
                g.fillRect(150, (CuartoDeAltura*2)+62, this.getWidth()-150, 4);
                g.fillRect(0, (CuartoDeAltura*3)+62, this.getWidth()-150, 4);
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Nivel1 = new javax.swing.JLabel();
        Nivel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Personaje = new Sprite.Personaje();
        jPanel1 = new javax.swing.JPanel();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 0));

        Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Nivel1.setText("Nivel 1");

        Nivel2.setText("Nivel 2");

        jLabel4.setText("Nivel 3");

        jLabel5.setText("Nivel 4");

        javax.swing.GroupLayout PersonajeLayout = new javax.swing.GroupLayout(Personaje);
        Personaje.setLayout(PersonajeLayout);
        PersonajeLayout.setHorizontalGroup(
            PersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        PersonajeLayout.setVerticalGroup(
            PersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(818, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Nivel1))
                .addGap(25, 25, 25))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Personaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Nivel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel5)
                .addGap(81, 81, 81)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(Nivel2)
                .addGap(124, 124, 124)
                .addComponent(Nivel1)
                .addGap(79, 79, 79)
                .addComponent(Personaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(Panel);
    }// </editor-fold>//GEN-END:initComponents
    public void AlturaD(){
        AlturaP = this.getHeight();
        CuartoDeAltura = (AlturaP-62)/4;
        System.out.println(""+AlturaP+" "+CuartoDeAltura);
    }
    public void Puertas(){
        Nivel1.setLocation((CuartoDeAltura*3)+62, this.getWidth()-75);
    }
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        //requestFocusInWindow();// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        this.repaint();
        xPersonaje = Personaje.getX();
        yPersonaje = Personaje.getY();
        System.out.println(""+xPersonaje);
        switch(evt.getKeyCode()){
            case KeyEvent.VK_W:
                yPersonaje-=8;
                Personaje.setLocation(xPersonaje, yPersonaje);
                Personaje.repaint();
                System.out.println("WW");
                break;
            case KeyEvent.VK_S:
                yPersonaje+=8;
                Personaje.setLocation(xPersonaje, yPersonaje);
                break;
            case KeyEvent.VK_A:
                xPersonaje-=8;
                Personaje.setLocation(xPersonaje, yPersonaje);
                break;
            case KeyEvent.VK_D:
                xPersonaje+=8;
                Personaje.setLocation(xPersonaje, yPersonaje);
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nivel1;
    private javax.swing.JLabel Nivel2;
    public static javax.swing.JPanel Panel;
    private Sprite.Personaje Personaje;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
