/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Niveles;

import static GUI.main.clic;
import static GUI.main.musica;
import static GUI.main.paneMain;
import static GUI.main.sonido;
import GUI.menuGame;
import Herramientas.Sound;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.util.Random;

/**
 *
 * @author angel
 */
public class level1 extends javax.swing.JPanel {
    boolean p1,p2,p3,p4,p5;
    int i=0,p=0,e=0;int PreguntasUSE[];
    public static Random rm = new Random();
    String vPreguntas[],mRespuestas[][];
    String  mensaje_cong = "!Great¡ correct asnwer";
    String mensaje_wrong = "!Upss¡ wrong answer";
    public static Sound correct = new Sound("/Sonidos/correct.wav");
    public static Sound incorrect = new Sound("/Sonidos/incorrect.wav");
    
    /**
     * Creates new form level1
     */
    public level1() {
        initComponents();
        Inicial();
        
    }
    public void Inicial(){
        mRespuestas = new String[7][3];
        vPreguntas = new String[7];
        vPreguntas[0] = "Select the word that corresponds to 'Rojo'";                //Pregunta 1
        vPreguntas[1] = "Select the word that corresponds to 'Perro'";               //Pregunta 2
        vPreguntas[2] = "Select the word that corresponds to 'Dos'";                 //Pregunta 3
        vPreguntas[3] = "Select the word that corresponds to 'Hola'";                //Pregunta 4
        vPreguntas[4] = "Select the word that corresponds to 'Ventana'";             //Pregunta 5
        mRespuestas[0][0]="Green";mRespuestas[0][1]="Blue";mRespuestas[0][2]="Red";    //Respuestas 1
        mRespuestas[1][0]="Cat";mRespuestas[1][1]="Dog";mRespuestas[1][2]="Lion";      //Respuestas 2
        mRespuestas[2][0]="Ten";mRespuestas[2][1]="One";mRespuestas[2][2]="Two";       //Respuestas 3
        mRespuestas[3][0]="Hello";mRespuestas[3][1]="Bye";mRespuestas[3][2]="Good";    //Respuestas 4
        mRespuestas[4][0]="Table";mRespuestas[4][1]="Cake";mRespuestas[4][2]="Window"; //Respuestas 5
        etiPregunta.setText(vPreguntas[i]);
        p3 = false; p2 = false;p1 = false;
        btn1.setActionCommand("btn1");
        btn2.setActionCommand("btn2");
        btn3.setActionCommand("btn3");
        RP1.setEnabled(true);
        RP2.setEnabled(false);
        RP3.setEnabled(false);
        RP4.setEnabled(false);
        RP5.setEnabled(false);
    }
    public void GeneradoPreguntas(){
        int t = 0;
        int n = 5;
        int numeros[] = new int[5];
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btns = new javax.swing.ButtonGroup();
        fondoL11 = new fondos.FondoL1();
        pTop = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        playBack = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        pDown = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        RP1 = new javax.swing.JLabel();
        RP2 = new javax.swing.JLabel();
        RP3 = new javax.swing.JLabel();
        RP4 = new javax.swing.JLabel();
        RP5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        pCenter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        etiPregunta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pImg1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JRadioButton();
        pImg2 = new javax.swing.JPanel();
        btn2 = new javax.swing.JRadioButton();
        pImg3 = new javax.swing.JPanel();
        btn3 = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        etiResultado = new javax.swing.JLabel();
        pRight = new javax.swing.JPanel();
        pLeft = new javax.swing.JPanel();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 0));

        fondoL11.setLayout(new java.awt.BorderLayout());

        pTop.setOpaque(false);
        pTop.setLayout(new java.awt.GridLayout(1, 2));

        jPanel7.setOpaque(false);

        playBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha-hacia-la-izquierda.png"))); // NOI18N
        playBack.setBorderPainted(false);
        playBack.setContentAreaFilled(false);
        playBack.setFocusPainted(false);
        playBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(playBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 234, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(playBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pTop.add(jPanel7);

        jPanel9.setOpaque(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        pTop.add(jPanel9);

        fondoL11.add(pTop, java.awt.BorderLayout.PAGE_START);

        pDown.setOpaque(false);
        pDown.setLayout(new java.awt.GridLayout(1, 2));

        jPanel5.setOpaque(false);

        RP1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RP1.setForeground(new java.awt.Color(247, 247, 247));
        RP1.setText("1");
        jPanel5.add(RP1);

        RP2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RP2.setForeground(new java.awt.Color(247, 247, 247));
        RP2.setText("2");
        jPanel5.add(RP2);

        RP3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RP3.setForeground(new java.awt.Color(247, 247, 247));
        RP3.setText("3");
        jPanel5.add(RP3);

        RP4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RP4.setForeground(new java.awt.Color(247, 247, 247));
        RP4.setText("4");
        jPanel5.add(RP4);

        RP5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RP5.setForeground(new java.awt.Color(247, 247, 247));
        RP5.setText("5");
        jPanel5.add(RP5);

        pDown.add(jPanel5);

        jPanel6.setOpaque(false);

        btnOk.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnOk.setText("Check");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel6.add(btnOk);

        pDown.add(jPanel6);

        fondoL11.add(pDown, java.awt.BorderLayout.PAGE_END);

        pCenter.setOpaque(false);
        pCenter.setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        etiPregunta.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        etiPregunta.setForeground(new java.awt.Color(248, 248, 248));
        jPanel1.add(etiPregunta, new java.awt.GridBagConstraints());

        pCenter.add(jPanel1);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 5));

        jPanel4.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        pImg1.setOpaque(false);
        pImg1.setLayout(new java.awt.GridBagLayout());

        btns.add(btn1);
        btn1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(247, 247, 247));
        btn1.setText("Green");
        btn1.setOpaque(false);
        pImg1.add(btn1, new java.awt.GridBagConstraints());

        jPanel2.add(pImg1);

        pImg2.setOpaque(false);
        pImg2.setLayout(new java.awt.GridBagLayout());

        btns.add(btn2);
        btn2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(247, 247, 247));
        btn2.setText("Blue");
        btn2.setOpaque(false);
        pImg2.add(btn2, new java.awt.GridBagConstraints());

        jPanel2.add(pImg2);

        pImg3.setOpaque(false);
        pImg3.setLayout(new java.awt.GridBagLayout());

        btns.add(btn3);
        btn3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(247, 247, 247));
        btn3.setText("Red");
        btn3.setOpaque(false);
        pImg3.add(btn3, new java.awt.GridBagConstraints());

        jPanel2.add(pImg3);

        jPanel8.setOpaque(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8);

        pCenter.add(jPanel2);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        etiResultado.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        etiResultado.setForeground(new java.awt.Color(248, 248, 248));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 298, 30, 270);
        jPanel3.add(etiResultado, gridBagConstraints);

        pCenter.add(jPanel3);

        fondoL11.add(pCenter, java.awt.BorderLayout.CENTER);

        pRight.setOpaque(false);

        javax.swing.GroupLayout pRightLayout = new javax.swing.GroupLayout(pRight);
        pRight.setLayout(pRightLayout);
        pRightLayout.setHorizontalGroup(
            pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pRightLayout.setVerticalGroup(
            pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fondoL11.add(pRight, java.awt.BorderLayout.WEST);

        pLeft.setOpaque(false);

        javax.swing.GroupLayout pLeftLayout = new javax.swing.GroupLayout(pLeft);
        pLeft.setLayout(pLeftLayout);
        pLeftLayout.setHorizontalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pLeftLayout.setVerticalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fondoL11.add(pLeft, java.awt.BorderLayout.EAST);

        add(fondoL11);
    }// </editor-fold>//GEN-END:initComponents
    public char btnDeterminar(char Sbtn){
        char btnS=' ';
        System.out.println("Selected Radio Button: " + btns.getSelection().getActionCommand());
        String value = btns.getSelection().getActionCommand();
        switch(value){
            case "btn1":
                btnS = '1';
                break;
            case "btn2":
                btnS = '2';
                break;
            case "btn3":
                btnS = '3';
                break;
            default:
                btnS='0';
    }       
        return btnS;
    }
    public void btnRC(){
                btn1.setEnabled(false);
                btn2.setEnabled(false);
                btn3.setEnabled(false);
                btnOk.setText("Next");
    }
    public void btnNormal(){
                btn1.setEnabled(true);
                btn2.setEnabled(true);
                btn3.setEnabled(true);
                btns.clearSelection();
                btnOk.setText("Check");
                etiResultado.setText(" ");
                RP1.setEnabled(false);
                RP2.setEnabled(false);
                RP3.setEnabled(false);
                RP4.setEnabled(false);
                RP5.setEnabled(false);
    }
    public void preg1(){
        char btnS = btnDeterminar(' ');
        RP1.setEnabled(true);
        switch(btnS){
            case '3':
                btnRC();
                etiResultado.setText(mensaje_cong);
                p1 = true;
                correct.reproducir();
                //RP1.setOpaque(true);
                i++;
                break;
            default:
                etiResultado.setText(mensaje_wrong );
                btns.clearSelection();
                e+=1;
                incorrect.reproducir();
                break;
        }
       
    }
    public void preg2(){
        if(i==1){    
            etiResultado.setVisible(false);
            etiPregunta.setText(vPreguntas[i]);
            btn1.setText(mRespuestas[i][0]);
            btn2.setText(mRespuestas[i][1]);
            btn3.setText(mRespuestas[i][2]);
            btnNormal();
            i++;
            RP2.setEnabled(true);
        }
        else{
            etiResultado.setVisible(true);
            
            char btnS = btnDeterminar(' ');
            switch(btnS){
                case '2':
                    btnRC();
                    etiResultado.setText(mensaje_cong);
                    p2 =true;
                    correct.reproducir();
                    break;
                default:
                    etiResultado.setText(mensaje_wrong );
                    btns.clearSelection();
                    e+=1;
                    incorrect.reproducir();
            }
        }
    }
    public void preg3(){
        if(i==2){
            etiResultado.setVisible(false);
            etiPregunta.setText(vPreguntas[i]);
            btn1.setText(mRespuestas[i][0]);
            btn2.setText(mRespuestas[i][1]);
            btn3.setText(mRespuestas[i][2]);
            btnNormal();
            i++;
            RP3.setEnabled(true);
        }
        else{
            etiResultado.setVisible(true);
            char btnS = btnDeterminar(' ');
            System.out.println(" "+btnS);
            switch(btnS){
                case '3':
                    btnRC();
                    etiResultado.setText(mensaje_cong);
                    p3 =true;
                    correct.reproducir();
                    break;
                default:
                    etiResultado.setText(mensaje_wrong );
                    btns.clearSelection();
                    e+=1;
                    incorrect.reproducir();
                    
            }
        }
    }
    public void preg4(){
        if(i==3){
            etiResultado.setVisible(false);
            etiPregunta.setText(vPreguntas[i]);
            btn1.setText(mRespuestas[i][0]);
            btn2.setText(mRespuestas[i][1]);
            btn3.setText(mRespuestas[i][2]);
            btnNormal();
            i++;
            RP4.setEnabled(true);
        }
        else{
            etiResultado.setVisible(true);
            char btnS = btnDeterminar(' ');
            switch(btnS){
                case '1':
                    btnRC();
                    etiResultado.setText(mensaje_cong);
                    p4 =true;
                    correct.reproducir();
                    break;
                default:
                    etiResultado.setText(mensaje_wrong );
                    btns.clearSelection();
                    e+=1;
                    incorrect.reproducir();
            }
        }
    }
    public void preg5(){
        if(i==4){
            etiResultado.setVisible(false);
            etiPregunta.setText(vPreguntas[i]);
            btn1.setText(mRespuestas[i][0]);
            btn2.setText(mRespuestas[i][1]);
            btn3.setText(mRespuestas[i][2]);
            btnNormal();
            i++;
            RP5.setEnabled(true);
        }
        else{
            etiResultado.setVisible(true);
            char btnS = btnDeterminar(' ');
            switch(btnS){
                case '3':
                    btnRC();
                    etiResultado.setText(mensaje_cong);
                    p5 =true;
                    correct.reproducir();
                    break;
                default:
                    etiResultado.setText(mensaje_wrong );
                    btns.clearSelection();
                    e+=1;
                    incorrect.reproducir();
            }
        }
    }
    private void playBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBackActionPerformed
        clic.reproducir();
        if(sonido){
        menuGame.musicaaa.stop();
        musica.repetir();
        }
        menuGame level = new menuGame();
        level.setLocation(0, 0);
        paneMain.removeAll();
        paneMain.add(level,GridLayout.class);
        paneMain.revalidate();
        paneMain.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_playBackActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
        }
    }//GEN-LAST:event_formKeyPressed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        clic.reproducir();
        if(btn1.isSelected()||btn2.isSelected()||btn3.isSelected()){
            System.out.println(""+e);
            if(!p1) preg1();
            else if(!p2) preg2();
            else if(!p3) preg3();
            else if(!p4) preg4();
            else if(!p5) preg5();
            else{
            nextLVL2 level = new nextLVL2();
            paneMain.removeAll();
            paneMain.add(level,GridLayout.class);
            paneMain.revalidate();
            paneMain.repaint();
            }
        }
        else{
            etiResultado.setText("Please select a option");
            incorrect.reproducir();
        }
    }//GEN-LAST:event_btnOkActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RP1;
    private javax.swing.JLabel RP2;
    private javax.swing.JLabel RP3;
    private javax.swing.JLabel RP4;
    private javax.swing.JLabel RP5;
    private javax.swing.JRadioButton btn1;
    private javax.swing.JRadioButton btn2;
    private javax.swing.JRadioButton btn3;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup btns;
    private javax.swing.JLabel etiPregunta;
    private javax.swing.JLabel etiResultado;
    private fondos.FondoL1 fondoL11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pDown;
    private javax.swing.JPanel pImg1;
    private javax.swing.JPanel pImg2;
    private javax.swing.JPanel pImg3;
    private javax.swing.JPanel pLeft;
    private javax.swing.JPanel pRight;
    private javax.swing.JPanel pTop;
    private javax.swing.JButton playBack;
    // End of variables declaration//GEN-END:variables
}
