/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Niveles;

import static UI.main.paneMain;
import UI.pLevel;
import java.awt.GridLayout;

/**
 *
 * @author Angel Flores
 */
public class nextLevel extends javax.swing.JPanel {

    /**
     * Creates new form nextLevel
     */
    public nextLevel() {
        
        initComponents();
        Msg.setText("CONGRATULATIONS YOU RAISE THE LEVEL");
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aviso = new javax.swing.JPanel();
        p11 = new javax.swing.JPanel();
        Msg = new javax.swing.JLabel();
        p20 = new javax.swing.JPanel();
        p22 = new javax.swing.JPanel();
        btnexit = new javax.swing.JButton();
        p24 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();

        aviso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        aviso.setEnabled(false);
        aviso.setOpaque(false);
        aviso.setLayout(new java.awt.GridLayout(2, 1));

        p11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 46));

        Msg.setText("Hola");
        p11.add(Msg);

        aviso.add(p11);

        p20.setLayout(new java.awt.GridLayout(1, 3));

        p22.setLayout(new java.awt.GridBagLayout());

        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        p22.add(btnexit, new java.awt.GridBagConstraints());

        p20.add(p22);

        p24.setLayout(new java.awt.GridBagLayout());

        btnNext.setText("NEXT LEVEL");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        p24.add(btnNext, new java.awt.GridBagConstraints());

        p20.add(p24);

        aviso.add(p20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        pLevel level = new pLevel();
        level.setLocation(0, 0);
        paneMain.removeAll();
        paneMain.add(level,GridLayout.class);
        paneMain.revalidate();
        paneMain.repaint();  
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        level2 level = new level2();
        level.setLocation(0, 0);
        paneMain.removeAll();
        paneMain.add(level,GridLayout.class);
        paneMain.revalidate();
        paneMain.repaint();  
    }//GEN-LAST:event_btnNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Msg;
    private javax.swing.JPanel aviso;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnexit;
    private javax.swing.JPanel p11;
    private javax.swing.JPanel p20;
    private javax.swing.JPanel p22;
    private javax.swing.JPanel p24;
    // End of variables declaration//GEN-END:variables
}
