/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Config.ImageFondo;
import java.awt.event.KeyEvent;


/**
 *
 * @author Angel Flores
 */
public class pLevel extends javax.swing.JPanel {

    /**
     * Creates new form pLevel
     */
    public pLevel() {
        initComponents();
        ImageFondo image=new ImageFondo();
        image.setImage("/img/fondo.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoL1 = new fondos.FondoL();
        goku = new Personajes.Goku();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout gokuLayout = new javax.swing.GroupLayout(goku);
        goku.setLayout(gokuLayout);
        gokuLayout.setHorizontalGroup(
            gokuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        gokuLayout.setVerticalGroup(
            gokuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoL1Layout = new javax.swing.GroupLayout(fondoL1);
        fondoL1.setLayout(fondoL1Layout);
        fondoL1Layout.setHorizontalGroup(
            fondoL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoL1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(goku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        fondoL1Layout.setVerticalGroup(
            fondoL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoL1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(goku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        add(fondoL1);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int x= goku.getBounds().x;
        int y= goku.getBounds().y;
        switch(evt.getKeyCode()){
            case KeyEvent.VK_W:
                y-=10;
                goku.setBounds(x, y, 200, 200);
                break;
            case KeyEvent.VK_S:
                y+=10;
                goku.setBounds(x, y, 200, 200);
                break;
            case KeyEvent.VK_D:
                x+=10;
                goku.setBounds(x, y, 200, 200);
                break;
            case KeyEvent.VK_A:
                x-=10;
                goku.setBounds(x, y, 200, 200);
                break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fondos.FondoL fondoL1;
    private Personajes.Goku goku;
    // End of variables declaration//GEN-END:variables
}
