/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Niveles.Level1;
import Niveles.Level2;
import Niveles.Level3;
import Niveles.Level4;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author uriel
 */
public class vDetermination extends javax.swing.JFrame {
 private static int a,h;
public int nivel_op;
    /**
     * Creates new form
     */
    public vDetermination() {
        initComponents(); 
        this.labelNose.setVisible(false);/* Inicialiazacion no visibles de los temas que contentra cada nivel*/
        this.labelPrincipiante.setVisible(false);
        this.labelAvanzado.setVisible(false);   
       this.labelIntermedio.setVisible(false);
       
        
    }
private void Display(){
        
}
private int Mensajes_slider(int valor){
   
     switch (valor ){
         case 4:this.labelNose.setText("Contiene....1" );
             this.labelNose.setVisible(true);
             this.labelPrincipiante.setVisible(false);
             
             break;
         case 3: this.labelPrincipiante.setText("cotnieneee 2");
             this.labelPrincipiante.setVisible(true);
             this.labelNose.setVisible(false);
             this.labelIntermedio.setVisible(false);
             
             break;
         case 2:  this.labelIntermedio.setText("cONTIENEEE 3");
             this.labelIntermedio.setVisible(true);
             this.labelPrincipiante.setVisible(false);
             this.labelAvanzado.setVisible(false);
             
             break;
         case 1:this.labelAvanzado.setText("COTNEIEEEEN 4");
             this.labelAvanzado.setVisible(true);
             this.labelIntermedio.setVisible(false);
             
             break;
             
     }
     
   return valor;
}

public void Avanzar_niveles(){
    nivel_op = this.Jslider.getValue();
     
        Level1 abrir1 = new Level1();
        Level2 abrir2 = new Level2();
        Level3 abrir3= new Level3();
        Level4 abrir4 = new Level4();
        
        switch(nivel_op){
            
            case 1: abrir4.setVisible(true);
                    this.setVisible(false);;
            break;
            case 2: abrir3.setVisible(true);
            this.setVisible(false);
            break;
            case 3: abrir2.setVisible(true);
            this.setVisible(false);
            break;
            case 4: abrir1.setVisible(true);
            this.setVisible(false);
                   break;
        } 
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelPrincipiante = new javax.swing.JLabel();
        labelAvanzado = new javax.swing.JLabel();
        labelNose = new javax.swing.JLabel();
        Jslider = new javax.swing.JSlider();
        etiNose = new javax.swing.JLabel();
        etiPrincipiante = new javax.swing.JLabel();
        etiIntermedio = new javax.swing.JLabel();
        Btn_next = new javax.swing.JButton();
        labelIntermedio = new javax.swing.JLabel();
        avanzado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        Contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("¿How much do you know English?");
        Contenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 290, 28));

        labelPrincipiante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrincipiante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Contenedor.add(labelPrincipiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 270, 68));

        labelAvanzado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Contenedor.add(labelAvanzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 240, 73));

        labelNose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNose.setText(" ");
        labelNose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Contenedor.add(labelNose, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 270, 54));

        Jslider.setMajorTickSpacing(1);
        Jslider.setMaximum(4);
        Jslider.setMinimum(1);
        Jslider.setOrientation(javax.swing.JSlider.VERTICAL);
        Jslider.setPaintTicks(true);
        Jslider.setValue(2);
        Jslider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                JsliderStateChanged(evt);
            }
        });
        Contenedor.add(Jslider, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 80, 420));

        etiNose.setText("No sé nada");
        Contenedor.add(etiNose, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 109, 34));

        etiPrincipiante.setText("Pincipiante");
        Contenedor.add(etiPrincipiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 96, -1));

        etiIntermedio.setText("Intermedio");
        Contenedor.add(etiIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 85, -1));

        Btn_next.setText("Next");
        Btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_nextActionPerformed(evt);
            }
        });
        Contenedor.add(Btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 150, 50));

        labelIntermedio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Contenedor.add(labelIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 240, 73));

        avanzado.setText("Avanzado");
        Contenedor.add(avanzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 110, 20));

        getContentPane().add(Contenedor);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JsliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JsliderStateChanged
        // TODO add your handling code here:
       int valor;
        valor = this.Jslider.getValue();
        this.Mensajes_slider(valor);
       
          
         
    }//GEN-LAST:event_JsliderStateChanged

    private void Btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_nextActionPerformed
        // TODO add your handling code here:
              Avanzar_niveles();
    }//GEN-LAST:event_Btn_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vDetermination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vDetermination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vDetermination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vDetermination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vDetermination().setVisible(true);
            }
            
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_next;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JSlider Jslider;
    private javax.swing.JLabel avanzado;
    private javax.swing.JLabel etiIntermedio;
    private javax.swing.JLabel etiNose;
    private javax.swing.JLabel etiPrincipiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAvanzado;
    private javax.swing.JLabel labelIntermedio;
    private javax.swing.JLabel labelNose;
    private javax.swing.JLabel labelPrincipiante;
    // End of variables declaration//GEN-END:variables
}
