/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author uriel
 */
public class vDeterminar_conocimiento extends javax.swing.JFrame {
 private static int a,h;
 
    /**
     * Creates new form vDeterminar_conocimiento
     */
    public vDeterminar_conocimiento() {
        initComponents(); 
        this.Label_principiante_contenido.setVisible(false);/* Inicialiazacion no visibles de los temas que contentra cada nivel*/
        this.Label_medio_contenido.setVisible(false);
        this.Label_avanzado_contenido.setVisible(false);   
       
        
    }
private void Display(){
        //Toolkit tk = Toolkit.getDefaultToolkit();
        //Dimension d= tk.getScreenSize();
        this.setUndecorated(rootPaneCheckingEnabled);
        //this.setSize(d);
        this.setExtendedState(MAXIMIZED_BOTH);
        //a= (int)d.getWidth();
        //h= (int)d.getHeight();
        System.out.println(" "+a+" "+h);
}
private int Mensajes_slider(int valor){
   
     
         if (valor == 3){
             this.Label_principiante_contenido.setText("Contiene....1" );
             this.Label_principiante_contenido.setVisible(true);
             this.Label_medio_contenido.setVisible(false);
         }
         else if (valor == 2){
             this.Label_medio_contenido.setText("cotnieneee 2");
             this.Label_medio_contenido.setVisible(true);
             this.Label_principiante_contenido.setVisible(false);
             this.Label_avanzado_contenido.setVisible(false);
         }
         else if (valor == 1){
             this.Label_avanzado_contenido.setText("cONTIENEEE 3");
             this.Label_avanzado_contenido.setVisible(true);
             this.Label_medio_contenido.setVisible(false);
         }
   return valor;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Label_medio_contenido = new javax.swing.JLabel();
        Label_avanzado_contenido = new javax.swing.JLabel();
        Label_principiante_contenido = new javax.swing.JLabel();
        Jslider = new javax.swing.JSlider();
        Etiqueta_prrincipiante = new javax.swing.JLabel();
        Etiqueta_inter = new javax.swing.JLabel();
        Etiqueta_avanzado = new javax.swing.JLabel();
        Btn_next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("¿How much do you know English?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 290, 28));

        Label_medio_contenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Label_medio_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 270, 68));

        Label_avanzado_contenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Label_avanzado_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 240, 73));

        Label_principiante_contenido.setText(" ");
        Label_principiante_contenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Label_principiante_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 270, 54));

        Jslider.setMajorTickSpacing(1);
        Jslider.setMaximum(3);
        Jslider.setMinimum(1);
        Jslider.setOrientation(javax.swing.JSlider.VERTICAL);
        Jslider.setPaintTicks(true);
        Jslider.setValue(2);
        Jslider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                JsliderStateChanged(evt);
            }
        });
        jPanel1.add(Jslider, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 80, 400));

        Etiqueta_prrincipiante.setText("Principiante");
        jPanel1.add(Etiqueta_prrincipiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 109, 34));

        Etiqueta_inter.setText("Intermedio");
        jPanel1.add(Etiqueta_inter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 96, -1));

        Etiqueta_avanzado.setText("Avanzado");
        jPanel1.add(Etiqueta_avanzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 85, -1));

        Btn_next.setText("Next");
        jPanel1.add(Btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 150, 50));

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JsliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JsliderStateChanged
        // TODO add your handling code here:
       int valor;
        valor = this.Jslider.getValue();
        this.Mensajes_slider(valor);
       
          
         
    }//GEN-LAST:event_JsliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vDeterminar_conocimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vDeterminar_conocimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vDeterminar_conocimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vDeterminar_conocimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vDeterminar_conocimiento().setVisible(true);
            }
            
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_next;
    private javax.swing.JLabel Etiqueta_avanzado;
    private javax.swing.JLabel Etiqueta_inter;
    private javax.swing.JLabel Etiqueta_prrincipiante;
    private javax.swing.JSlider Jslider;
    private javax.swing.JLabel Label_avanzado_contenido;
    private javax.swing.JLabel Label_medio_contenido;
    private javax.swing.JLabel Label_principiante_contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
