/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Config.Config;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;



/**
 *
 * @author Angel Flores
 */
public class vLevel extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public vLevel(){
        
        Dis();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pCenter = new javax.swing.JPanel();
        pLevel1 = new javax.swing.JPanel();
        btnLevel1 = new javax.swing.JButton();
        pLevel2 = new javax.swing.JPanel();
        btnLevel2 = new javax.swing.JButton();
        pLevel3 = new javax.swing.JPanel();
        btnLevel3 = new javax.swing.JButton();
        pLevel4 = new javax.swing.JPanel();
        btnLevel4 = new javax.swing.JButton();
        pTop = new javax.swing.JPanel();
        pTGrid = new javax.swing.JPanel();
        pHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        pTitle = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        pE = new javax.swing.JPanel();
        pDown = new javax.swing.JPanel();
        pLeft = new javax.swing.JPanel();
        pRight = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pCenter.setLayout(new java.awt.GridLayout(1, 4));

        pLevel1.setLayout(new java.awt.GridBagLayout());

        btnLevel1.setText("Level 1");
        pLevel1.add(btnLevel1, new java.awt.GridBagConstraints());

        pCenter.add(pLevel1);

        pLevel2.setLayout(new java.awt.GridBagLayout());

        btnLevel2.setText("Level 2");
        pLevel2.add(btnLevel2, new java.awt.GridBagConstraints());

        pCenter.add(pLevel2);

        pLevel3.setLayout(new java.awt.GridBagLayout());

        btnLevel3.setText("Level 3");
        pLevel3.add(btnLevel3, new java.awt.GridBagConstraints());

        pCenter.add(pLevel3);

        pLevel4.setLayout(new java.awt.GridBagLayout());

        btnLevel4.setText("Level 4");
        pLevel4.add(btnLevel4, new java.awt.GridBagConstraints());

        pCenter.add(pLevel4);

        getContentPane().add(pCenter, java.awt.BorderLayout.CENTER);

        pTop.setLayout(new java.awt.GridLayout(1, 0));

        pTGrid.setLayout(new java.awt.GridLayout(1, 3));

        pHome.setLayout(new java.awt.GridBagLayout());

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pHome.add(btnHome, new java.awt.GridBagConstraints());

        pTGrid.add(pHome);

        pTitle.setLayout(new java.awt.GridBagLayout());

        Title.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Title.setText("Levels");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 29, 42, 30);
        pTitle.add(Title, gridBagConstraints);

        pTGrid.add(pTitle);

        javax.swing.GroupLayout pELayout = new javax.swing.GroupLayout(pE);
        pE.setLayout(pELayout);
        pELayout.setHorizontalGroup(
            pELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        pELayout.setVerticalGroup(
            pELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        pTGrid.add(pE);

        pTop.add(pTGrid);

        getContentPane().add(pTop, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout pDownLayout = new javax.swing.GroupLayout(pDown);
        pDown.setLayout(pDownLayout);
        pDownLayout.setHorizontalGroup(
            pDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        pDownLayout.setVerticalGroup(
            pDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pDown, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout pLeftLayout = new javax.swing.GroupLayout(pLeft);
        pLeft.setLayout(pLeftLayout);
        pLeftLayout.setHorizontalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pLeftLayout.setVerticalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        getContentPane().add(pLeft, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout pRightLayout = new javax.swing.GroupLayout(pRight);
        pRight.setLayout(pRightLayout);
        pRightLayout.setHorizontalGroup(
            pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pRightLayout.setVerticalGroup(
            pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        getContentPane().add(pRight, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void Dis(){
        Config cfg = new Config();
        boolean fullscreen = Boolean.parseBoolean(cfg.getProperty("fullscreen"));
        System.out.println(fullscreen);
        if(fullscreen){
            this.setExtendedState(MAXIMIZED_BOTH);
            this.setUndecorated(rootPaneCheckingEnabled);
            System.out.println("1");
        }
        else{
            this.setPreferredSize(new Dimension(800, 600));
        }
    }
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        vStart abrir = new vStart();
        abrir.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vLevel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLevel1;
    private javax.swing.JButton btnLevel2;
    private javax.swing.JButton btnLevel3;
    private javax.swing.JButton btnLevel4;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pDown;
    private javax.swing.JPanel pE;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pLeft;
    private javax.swing.JPanel pLevel1;
    private javax.swing.JPanel pLevel2;
    private javax.swing.JPanel pLevel3;
    private javax.swing.JPanel pLevel4;
    private javax.swing.JPanel pRight;
    private javax.swing.JPanel pTGrid;
    private javax.swing.JPanel pTitle;
    private javax.swing.JPanel pTop;
    // End of variables declaration//GEN-END:variables
}
